spring: 
  datasource: 
    url: jdbc:h2:tcp://localhost/~/test
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create