spring:
  application:
    name: gestion-empleados
#  data:
#    mongodb:
#      host: localhost
#      port: 27018
#      username: admin
#      password: admin
#      database: DB_Proyectos
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.0