CREATE TABLE IF NOT EXISTS USUARIOS (
	ID BIGINT PRIMARY KEY,
	NOMBRE VARCHAR(255) NOT NULL,
	CORREO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLES (
	ID BIGINT PRIMARY KEY,
	NOMBRE VARCHAR(255) NOT NULL,
	DESC VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS PERMISOS (
	ID_ROL BIGINT NOT NULL,
	PERMISO VARCHAR(255) NOT NULL
);

ALTER TABLE PERMISOS
	ADD CONSTRAINT ID_PERMISO UNIQUE (ID_ROL, PERMISO)